// flow-typed signature: d5b8a6796f8d451fec557711337f0d78
// flow-typed version: <<STUB>>/scss-loader_v0.0.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scss-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scss-loader' {
  declare module.exports: any;
}
