const INITIAL_GAME_SETUP = 'INITIAL_GAME_SETUP';
const GAME_LOOP = 'GAME_LOOP';
const FINISHED_GAME = 'FINISHED_GAME';

const GAME_STAGES = {
  INITIAL_GAME_SETUP,
  GAME_LOOP,
  FINISHED_GAME
};

export default GAME_STAGES;
